# Practice Lab: Decision Trees





## 1 - Packages
First, let's run the cell below to import all the packages that you will need during this assignment.

In [3]:
import numpy as np
import matplotlib.pyplot as plt
from public_tests import *
from utils import *

%matplotlib inline

## 2 - Dataset
we have 10 examples of mushrooms. For each example, we have
Three features
Cap Color (Brown or Red),
 Stalk Shape (Tapering (as in \/) or Enlarging (as in /\)), and
Solitary (Yes or No)

Label
Edible (1 indicating yes or 0 indicating poisonous)


## One hot encoded dataset
For ease of implementation, we have one-hot encoded the features (turned them into 0 or 1 valued features)
therefore,

X_train contains three features for each example

Brown Color (A value of 1 indicates "Brown" cap color and 0 indicates "Red" cap color)

Tapering Shape (A value of 1 indicates "Tapering Stalk Shape" and 0 indicates "Enlarging" stalk shape)

Solitary (A value of 1 indicates "Yes" and 0 indicates "No")

y_train is whether the mushroom is edible

y = 1 indicates edible

y = 0 indicates poisonous


In [4]:
X_train = np.array([[1,1,1],[1,0,1],[1,0,0],[1,0,0],[1,1,1],[0,1,1],[0,0,0],[1,0,1],[0,1,0],[1,0,0]])
y_train = np.array([1,1,0,0,1,0,0,1,1,0])

In [5]:
print("First few elements of X_train:\n", X_train[:5])
print("Type of X_train:",type(X_train))

First few elements of X_train:
 [[1 1 1]
 [1 0 1]
 [1 0 0]
 [1 0 0]
 [1 1 1]]
Type of X_train: <class 'numpy.ndarray'>


In [6]:
print("First few elements of y_train:", y_train[:5])
print("Type of y_train:",type(y_train))

First few elements of y_train: [1 1 0 0 1]
Type of y_train: <class 'numpy.ndarray'>


In [7]:
print ('The shape of X_train is:', X_train.shape)
print ('The shape of y_train is: ', y_train.shape)
print ('Number of training examples (m):', len(X_train))

The shape of X_train is: (10, 3)
The shape of y_train is:  (10,)
Number of training examples (m): 10


# 4 - Decision Tree Refresher 




## Calculate entropy


## Exercise 1



In [67]:
# UNQ_C1
# GRADED FUNCTION: compute_entropy
def compute_entropy(y):

 
 entropy = 0.

 if len(y) != 0:
   
     p1 = len(y[y == 1]) / len(y)
   
     if p1 != 0 and p1 != 1:
        
         entropy = -p1 * np.log2(p1) - (1 - p1) * np.log2(1 - p1)
     else:
         entropy = 0.        

 return entropy

 You can check if your implementation was correct by running the following test code:

In [9]:
print("Entropy at root node: ", compute_entropy(y_train)) 

# UNIT TESTS
compute_entropy_test(compute_entropy)

Entropy at root node:  1.0
 All tests passed.


## Split dataset



## Exercise 2
For each index in node_indices

If the value of X at that index for that feature is 1, add the index to left_indices

If the value of X at that index for that feature is 0, add the index to right_indices



In [68]:
# UNQ_C2
# GRADED FUNCTION: split_dataset
def split_dataset(X, node_indices, feature):
   
    left_indices = []
    right_indices = []
    
    for i in node_indices:   
       if X[i][feature] == 1:
        
           left_indices.append(i)
       else:
           right_indices.append(i)
        
    return left_indices, right_indices

 Now, let's check our implementation

In [38]:
!pip install pydot
!pip install pydotplus
!pip install graphviz




  Created wheel for pydotplus: filename=pydotplus-2.0.2-py3-none-any.whl size=24575 sha256=cf6a9f415af906b3270ef678ebed17bcb90f5e0605cdfb1fce4279e9980dfab0
  Stored in directory: c:\users\madinalaptops\appdata\local\pip\cache\wheels\89\e5\de\6966007cf223872eedfbebbe0e074534e72e9128c8fd4b55eb
Successfully built pydotplus


In [43]:

root_indices = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

# The dataset only has three features, so this value can be 0 (Brown Cap), 1 (Tapering Stalk Shape) or 2 (Solitary)
feature = 0

left_indices, right_indices = split_dataset(X_train, root_indices, feature)

print("Left indices: ", left_indices)
print("Right indices: ", right_indices)

# Visualize the split 
# generate_split_viz(root_indices, left_indices, right_indices, feature)

# UNIT TESTS    
split_dataset_test(split_dataset)

Left indices:  [0, 1, 2, 3, 4, 7, 9]
Right indices:  [5, 6, 8]
 All tests passed.


## 4.3 Calculate information gain
Next, we'll write a function called information_gain that takes in the training data, the indices at a node and a feature to split on and returns the information gain from the split.


## Exercise 3
 compute_information_gain() function shown below to compute

Information Gain=𝐻(𝑝node1)−(𝑤left𝐻(𝑝left1)+𝑤right𝐻(𝑝right1))

In [44]:
# UNQ_C3
# GRADED FUNCTION: compute_information_gain

def compute_information_gain(X, y, node_indices, feature):
   # Split dataset
   left_indices, right_indices = split_dataset(X, node_indices, feature)

   # Some useful variables
   X_node, y_node = X[node_indices], y[node_indices]
   X_left, y_left = X[left_indices], y[left_indices]
   X_right, y_right = X[right_indices], y[right_indices]

   # You need to return the following variables correctly
   information_gain = 0

   ### START CODE HERE ###
  
   node_entropy = compute_entropy(y_node)
   left_entropy = compute_entropy(y_left)
   right_entropy = compute_entropy(y_right)

   w_left = len(X_left) / len(X_node)

   
   w_right = len(X_right) / len(X_node)

   weighted_entropy = w_left * left_entropy + w_right * right_entropy

   information_gain = node_entropy - weighted_entropy
 

   return information_gain

we can now check our implementation using the cell below and calculate what the information gain would be from splitting on each of the featues

In [45]:
info_gain0 = compute_information_gain(X_train, y_train, root_indices, feature=0)
print("Information Gain from splitting the root on brown cap: ", info_gain0)

info_gain1 = compute_information_gain(X_train, y_train, root_indices, feature=1)
print("Information Gain from splitting the root on tapering stalk shape: ", info_gain1)

info_gain2 = compute_information_gain(X_train, y_train, root_indices, feature=2)
print("Information Gain from splitting the root on solitary: ", info_gain2)

# UNIT TESTS
compute_information_gain_test(compute_information_gain)

Information Gain from splitting the root on brown cap:  0.034851554559677034
Information Gain from splitting the root on tapering stalk shape:  0.12451124978365313
Information Gain from splitting the root on solitary:  0.2780719051126377
 All tests passed.


## 4.4 Get best split
Now let's write a function to get the best feature to split on by computing the information gain from each feature as we did above and returning the feature that gives the maximum information gain


## Exercise 4
lets complete the get_best_split() function shown below.

The function takes in the training data, along with the indices of datapoint at that node

The output of the function is the feature that gives the maximum information gain



In [63]:
# UNQ_C4
# GRADED FUNCTION: get_best_split

def get_best_split(X, y, node_indices):   

    
    # Some useful variables
    num_features = X.shape[1]
    
    # You need to return the following variables correctly
    best_feature = -1
    
    max_info_gain = 0

   
    for feature in range(num_features): 

      
       info_gain = compute_information_gain(X, y, node_indices, feature)

       
       if info_gain > max_info_gain:  
           
           max_info_gain = info_gain
           best_feature =  feature  
   
    return best_feature


In [64]:
best_feature = get_best_split(X_train, y_train, root_indices)
print("Best feature to split on: %d" % best_feature)

# UNIT TESTS
get_best_split_test(get_best_split)

Best feature to split on: 2
 All tests passed.


 As we saw above, the function returns that the best feature to split on at the root node is feature 2 ("Solitary")


## 5 - Building the tree

In this section, we use the functions you implemented above to generate a decision tree by successively picking the best feature to split on until we reach the stopping criteria (maximum depth is 2).



In [65]:
# Not graded
tree = []

def build_tree_recursive(X, y, node_indices, branch_name, max_depth, current_depth):
    """
    Build a tree using the recursive algorithm that split the dataset into 2 subgroups at each node.
    This function just prints the tree.
    
    Args:
        X (ndarray):            Data matrix of shape(n_samples, n_features)
        y (array like):         list or ndarray with n_samples containing the target variable
        node_indices (ndarray): List containing the active indices. I.e, the samples being considered in this step.
        branch_name (string):   Name of the branch. ['Root', 'Left', 'Right']
        max_depth (int):        Max depth of the resulting tree. 
        current_depth (int):    Current depth. Parameter used during recursive call.
   
    """ 

    # Maximum depth reached - stop splitting
    if current_depth == max_depth:
        formatting = " "*current_depth + "-"*current_depth
        print(formatting, "%s leaf node with indices" % branch_name, node_indices)
        return
   
    # Otherwise, get best split and split the data
    # Get the best feature and threshold at this node
    best_feature = get_best_split(X, y, node_indices) 
    
    formatting = "-"*current_depth
    print("%s Depth %d, %s: Split on feature: %d" % (formatting, current_depth, branch_name, best_feature))
    
    # Split the dataset at the best feature
    left_indices, right_indices = split_dataset(X, node_indices, best_feature)
    tree.append((left_indices, right_indices, best_feature))
    
    # continue splitting the left and the right child. Increment current depth
    build_tree_recursive(X, y, left_indices, "Left", max_depth, current_depth+1)
    build_tree_recursive(X, y, right_indices, "Right", max_depth, current_depth+1)

In [69]:
build_tree_recursive(X_train, y_train, root_indices, "Root", max_depth=2, current_depth=0)
#generate_tree_viz(root_indices, y_train, tree)

 Depth 0, Root: Split on feature: 2
- Depth 1, Left: Split on feature: 0
  -- Left leaf node with indices [0, 1, 4, 7]
  -- Right leaf node with indices [5]
- Depth 1, Right: Split on feature: 1
  -- Left leaf node with indices [8]
  -- Right leaf node with indices [2, 3, 6, 9]
